### PR TITLE
feat(plugin-video): add video plugin to render Youtube/Vimeo video

### LINKED ISSUE #35: Add support for embedding videos
While we can embed videos using HTML like this:

```markdown
<iframe width="560" height="315" src="https://www.youtube.com/embed/dQw4w9WgXcQ?si=n1PmPV5KwExea0aZ&amp;controls=0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
```

It's cleaner to just use the video ID or URL:
```markdown
@[youtube](dQw4w9WgXcQ)
@[vimeo](https://vimeo.com/347119375)
```

image

### PR DESCRIPTION
**Pull request by maisonsmd**
Fix #35

Render video using its ID or URL.
Currently support Youtube & Vimeo.

This is a ported version of [marked-it-video](https://github.com/CenterForOpenScience/markdown-it-video)

eg:
image

### CODE REVIEW

**Comment by BearToCode** [comment]
Hello,
Thanks for creating this plugin. However, I feel like is better for this plugin to be a different repository. That's because it's not a

**Comment by maisonsmd** [comment]
@BearToCode 

Yeah that's not a problem. This main repo should not be bombarded with plugins either 😉
Please reject this PR.

Thanks.

**Comment by BearToCode** [comment]
Thank you, just reply here or create a new issue with the link to the repo when you're ready

**Comment by maisonsmd** [comment]
Hi @BearToCode 
I published the plugin to npm here: [carta-plugin-video](https://www.npmjs.com/package/carta-plugin-video).
There are 2 more if you're interested in: 
- [carta-plugin-imsize](https://www.npmjs.com/package/carta-plugin-imsize)
- [carta-plugin-subscript](https://www.npmjs.com/package/carta-plugin-subscript)

**Comment by BearToCode** [comment]
Hi again!

I added mentions to the plugins in the README as well as in a new dedicated section in the docs. Thank you for contributing to this package! ❤️

**Pull request closed without merging**
