### PR TITLE
[plugin-emoji] improvements

### LINKED ISSUE #90: [plugin-emoji] default css is a little wonky
I adjusted my own instance with:

```js
  import '@cartamd/plugin-emoji/default.css'
  import './css/emoji.css'
```

where _emoji.css_ includes the following overrides:

```css
.carta-emoji {
  display: block !important;
  word-break: break-word !important;
  overflow-x: auto;
  overflow-y: auto !important;
}

.carta-emoji button {
  display: inline-block !important;
  margin: 3px;
  height: 2rem;
  aspect-ratio: unset !important;
  white-space: nowrap;
}
```

to summarize:
* the main issue is that several emoji codes each resolve to a sequence of unicode characters
* the [default css](https://github.com/BearToCode/carta/blob/%40cartamd/plugin-emoji-v4.0.3/packages/plugin-emoji/src/lib/default.css) uses a grid layout, so an extra wide button stretches the width of an entire column
* the [default css](https://github.com/BearToCode/carta/blob/%40cartamd/plugin-emoji-v4.0.3/packages/plugin-emoji/src/lib/default.css) uses an aspect ratio of 1, so an extra wide button is also made extra tall.. and stretches the height of an entire row

test case:
1. type: `:h`
2. type: `:he`
3. type: `:hea`
   - several of the _heart_ emojis are multi character

### LINKED ISSUE #91: [plugin-emoji] mouse click event doesn't select emoji from filtered list
keyboard events work great (ie: arrows to change focus, enter to select).. but mouse events don't.

not a deal breaker.. but worthy of a quick mention.

### PR DESCRIPTION
**Pull request by warren-bank**
fix #90 
fix #91

### CODE REVIEW

**Comment by warren-bank** [comment]
Your [commit](https://github.com/BearToCode/carta/pull/92/commits/d0d067a6ed294f20c789dd4978286e9785049502) reverts the css back to a 8-column grid layout. Any reason? Imho, it [doesn't look very good](https://beartocode.github.io/carta/examples).

**Comment by BearToCode** [comment]
Hi, thanks for helping improving the library!

So, I tried your changes and many emoji buttons started to become un-aligned:
Screenshot (32)

While the previous/updated css looks fine:
Screenshot (33)

I don't see anything wrong using a grid layout. I read your issue #90 but I couldn't reproduce the bug you talked about. Am I missing something?

**Comment by warren-bank** [comment]
note to self.. the quick and dirty way to force the [online example](https://beartocode.github.io/carta/examples) to use the _default_ theme:

```js
{
  [...document.querySelectorAll('.carta-theme__github')].forEach(el => {
    el.classList.replace('carta-theme__github', 'carta-theme__default')
  });

  [
    'https://unpkg.com/carta-md@4.3.1/dist/default.css',
    'https://unpkg.com/@cartamd/plugin-emoji@4.0.4/dist/default.css'
  ].forEach(url => {
    const el = document.createElement('link')
    el.setAttribute('rel', 'stylesheet')
    el.setAttribute('href', url)
    document.head.appendChild(el)
  });
}
```

---

using `:hea` as the example..
this is the HTML markup for the popup:

```html
<div class="carta-emoji carta-theme__default" style="position: fixed; left: 400.5px; right: unset; top: unset; bottom: 44px;">
  <button class="carta-active" title="heart_eyes">😍 </button>
  <button class="" title="smiling_face_with_three_hearts">🥰 </button>
  <button class="" title="kissing_heart">😘 </button>
  <button class="" title="exploding_head">🤯 </button>
  <button class="" title="face_with_head_bandage">🤕 </button>
  <button class="" title="heart_eyes_cat">😻 </button>
  <button class="" title="speaking_head">🗣 </button>
  <button class="" title="woman_with_headscarf">🧕 </button>
  <button class="" title="woman_health_worker">👩‍⚕️ </button>
  <button class="" title="man_health_worker">👨‍⚕️ </button>
  <button class="" title="couple_with_heart_woman_man">💑 </button>
  <button class="" title="couple_with_heart_woman_woman">👩‍❤️‍👩 </button>
  <button class="" title="couple_with_heart_man_man">👨‍❤️‍👨 </button>
  <button class="" title="hear_no_evil">🙉 </button>
  <button class="" title="headphones">🎧 </button>
  <button class="" title="heart">❤️ </button>
  <button class="" title="orange_heart">🧡 </button>
  <button class="" title="yellow_heart">💛 </button>
  <button class="" title="green_heart">💚 </button>
  <button class="" title="blue_heart">💙 </button>
  <button class="" title="purple_heart">💜 </button>
  <button class="" title="black_heart">🖤 </button>
  <button class="" title="broken_heart">💔 </button>
  <button class="" title="heavy_heart_exclamation">❣ </button>
  <button class="" title="two_hearts">💕 </button>
  <button class="" title="revolving_hearts">💞 </button>
  <button class="" title="heartbeat">💓 </button>
  <button class="" title="heartpulse">💗 </button>
  <button class="" title="sparkling_heart">💖 </button>
  <button class="" title="gift_heart">💝 </button>
  <button class="" title="heart_decoration">💟 </button>
  <button class="" title="arrow_heading_up">⤴️ </button>
  <button class="" title="arrow_heading_down">⤵️ </button>
  <button class="" title="heavy_check_mark">✔️ </button>
  <button class="" title="heavy_plus_sign">➕ </button>
  <button class="" title="heavy_minus_sign">➖ </button>
  <button class="" title="heavy_division_sign">➗ </button>
  <button class="" title="heavy_multiplication_x">✖️ </button>
  <button class="" title="heavy_dollar_sign">💲 </button>
  <button class="" title="hearts">♥️ </button>
</div>
```

maybe this is OS dependent, but in my browser..
both `:couple_with_heart_woman_woman:` and `:couple_with_heart_man_man:` (for example) are 3 characters wide.

when using a grid layout and having elements that vary in width (as they do on my system), the grid doesn't work.
before when aspect ratio was `1`.. they broke __really__ badly.

currently, when the elements in a grid layout are forced to be a fixed size (ie: 2rem x 2rem).. it's causing the wider elements to overflow slightly and then the rest is truncated.

carta

admittedly, the css in my PR allowed the elements to expand their widths as needed and the ends of the rows don't align perfectly. But all elements are fully visible, and the rows wrap when needed.. when there isn't enough space to fit the next element (without requiring horizontal scrollbars).

**Comment by warren-bank** [comment]
thought.. as a test on your system.. could you try my css and then add `min-width: 2rem` (or possibly `2.5rem`) to see if that makes the ends of your rows stay aligned. I can't reproduce.. so I can't test.

since your emoji sequences are treated as a single character.. alignment should be pretty easy.. by setting a "minimum" width that's actually based more on your maximum width.. so all characters are the same width.

but if emoji sequences aren't treated in this manner.. then the buttons are free to grow.

**Comment by warren-bank** [comment]
going offline for a while.. gotta crash.. been up all night coding.. ttyl

**Comment by BearToCode** [comment]
I tried the examples you providde and all emojis are single character. I'm currently using Windows and Firefox.
What OS/distro are you using?

Good idea with the `min-width`! Seems to be working fine. Let me know tomorrow if we can proceed with that. Thanks ❤️ !

**Comment by warren-bank** [comment]
for comparison.. this patch reverts the css to my proposal

```js
{
  [...document.querySelectorAll('.carta-theme__github')].forEach(el => {
    el.classList.replace('carta-theme__github', 'carta-theme__default')
  });

  [
    'https://unpkg.com/carta-md@4.3.1/dist/default.css',
    'https://unpkg.com/@cartamd/plugin-emoji@4.0.4/dist/default.css'
  ].forEach(url => {
    const el = document.createElement('link')
    el.setAttribute('rel', 'stylesheet')
    el.setAttribute('href', url)
    document.head.appendChild(el)
  });

  [
    '.carta-emoji {display: block !important; width: 18rem;} .carta-emoji button {width: unset !important;}'
  ].forEach(css => {
    const el = document.createElement('style')
    el.textContent = css
    document.head.appendChild(el)
  });
}
```

carta

My OS doesn't have emoji support.. so this is rendered entirely by the browser.
I suppose that I'm not the best person to be testing, because my system is uncommon.
This is how it looks in Firefox Developer 97.
Chrome 109 must defer its emojis to the OS, because most of them display as gibberish.
I'll check how it looks in both a newer version of Firefox, and on Android..

**Comment by warren-bank** [comment]
hmm.. the Emoji component doesn't display on Android.. I tried several different browsers.
I'm guessing it just needs to add touch event listeners.. in addition to keydown, etc.
On the upside, when the emoji code is written out entirely by hand, it renders fine.

**Comment by warren-bank** [comment]
ok.. PR #93 adjusts the event handlers in the _Emoji_ component.. so the popup dialog works the same on mobile as it does on desktop.

tested on Android 7 (my TV box) in Chrome.. and the emojis look more like the screenshot of your desktop (than my desktop).

I don't know if what I'm seeing on my desktop would be common or uncommon.. but if it was me.. I'd do away with the grid layout and allow the buttons to be whatever width they want to be (with an sane minimum). It's possible that the text could be justified.. so whitespace in a row is more evently distributed; not sure if that's (a) possible, or (b) better looking.. TBD.

**Comment by warren-bank** [comment]
just played around a little with the CSS.. and using a flexbox layout seems like a very good compromise.

here is the patch to do a quick test on [this page](https://beartocode.github.io/carta/examples):

```js
{
  [...document.querySelectorAll('.carta-theme__github')].forEach(el => {
    el.classList.replace('carta-theme__github', 'carta-theme__default')
  });

  [
    'https://unpkg.com/carta-md@4.3.1/dist/default.css',
    'https://unpkg.com/@cartamd/plugin-emoji@4.0.4/dist/default.css'
  ].forEach(url => {
    const el = document.createElement('link')
    el.setAttribute('rel', 'stylesheet')
    el.setAttribute('href', url)
    document.head.appendChild(el)
  });

  [
    '.carta-emoji {display: flex !important; width: 18rem; flex-wrap: wrap; justify-content: space-evenly;} .carta-emoji button {width: unset !important;}'
  ].forEach(css => {
    const el = document.createElement('style')
    el.textContent = css
    document.head.appendChild(el)
  });
}
```

the important bit is:

```css
.carta-emoji {
  display: flex;
  width: 18rem;
  flex-wrap: wrap;
  justify-content: space-evenly;
}

.carta-emoji button {
  width: unset !important;
}
```

**Pull request merged**
