### PR TITLE
minor improvements

### PR DESCRIPTION
**Pull request by warren-bank**
1. 'italic' menu icon
   - `input.toggleSelectionSurrounding('*')`
2. prefixes
   - update all `defaultPrefixes`
   - note: also expands return type for `prefix.match`
3. pass `value` to 'Renderer' component one-way
   ```javascript
    <Renderer {value} />
   ```

### CODE REVIEW

**Comment by BearToCode** [comment]
Thanks for your contribution, could you please allow edits by maintainers? There are a couple thing I'd like to change

**Comment by warren-bank** [comment]
both `PR-*` branches now allow edits.

PS: since your comment, I've added one more commit to this branch.
(The regex for fenced code blocks wasn't detecting languages when the closing token was indented.)

PPS: I'm sure that you're aware of the race condition involving the highlighter.. new languages are loaded by the `Input` component at the same time that the `code` plugin is trying to use them. By default, this throws an uncaught exception. It wouldn't be a bad idea to suggest in the [README](https://github.com/BearToCode/carta/blob/master/packages/plugin-code/README.md#extension) for the `code` plugin to include the option:
```js
  const carta = new Carta({
    extensions: [
      code({
        onError: () => {}
      })
    ]
  })
```
..to prevent throwing an exception, and silently ignore the error.

The next time the user makes any edit to the markdown input, the newly loaded languages will be used to style the rendered HTML.

**Comment by BearToCode** [comment]
I'll merge this for now, thanks :)

Could you please provide an example of the highlighter issue you mentioned?

**Comment by warren-bank** [comment]
I'm happy to see these updates merged. This is a great project! Very nicely done.

Regarding my earlier comment about a race condition involving `highlighter` and the `code` extension,
here is a breakdown..

---

https://github.com/BearToCode/carta/blob/carta-md-v4.2.0/packages/carta-md/src/lib/internal/components/Input.svelte#L98
https://github.com/BearToCode/carta/blob/carta-md-v4.2.0/packages/carta-md/src/lib/internal/components/Input.svelte#L93
```js
  const highlightNestedLanguages = debounce(async (text: string) => {
    const highlighter = await carta.highlighter();
    const { updated } = await loadNestedLanguages(highlighter, text);
    if (updated) highlight(text);
  }, 300);

  $: highlightNestedLanguages(value);
```

https://github.com/BearToCode/carta/blob/carta-md-v4.2.0/packages/carta-md/src/lib/internal/components/Renderer.svelte#L39
https://github.com/BearToCode/carta/blob/carta-md-v4.2.0/packages/carta-md/src/lib/internal/components/Renderer.svelte#L31
```js
  const debouncedRenderer = debounce(() => {
    carta
      .render(value)
      .then((rendered) => (renderedHtml = rendered))
      .then(() => events('render', void 0));
  }, carta.rendererDebounce ?? 300);

  $: debouncedRenderer(value);
```

https://github.com/BearToCode/carta/blob/carta-md-v4.2.0/packages/carta-md/src/lib/internal/carta.ts#L388
```js
  public async render(markdown: string): Promise<string> {
    const processor = await this.asyncProcessor;
    const dirty = String(await processor.process(markdown));
    if (!dirty) return '';
    this.dispatcher.dispatchEvent(
      new CustomEvent<{ carta: Carta }>('carta-render', { detail: { carta: this } })
    );
    return (this.sanitizer && this.sanitizer(dirty)) ?? dirty;
  }
```

---

### summary:

`MarkdownEditor` component includes both `Input` and `Renderer` components
- `Input` component includes a `textarea` and its `value` is export
   * when it changes, it detects the list of languages used by fenced code blocks and dynamically loads them into `highlighter`
- `Renderer` components has an input `value` prop
   * when it changes, remark processes the new `value` and updates its rendered HTML
   * the `code` remark extension uses the same instance of `highlighter`
   * when the updated value adds a new fenced code block but the language hasn't yet been loaded into `highlighter`, the the `code` remark extension throws an error:
     ```text
       Uncaught (in promise) ShikiError: Language `xxx` not found, you may need to load it first
     ```

### notes:

* the simplest way to trigger this race condition is to copy/paste a blob of markdown into the `Input` component's textarea
* I can't reproduce in your [online demo](https://beartocode.github.io/carta/examples#github)
  - pretty sure it's because the `GitHubExample` uses `tab` mode, rather than `split` or `auto`
  - presumably, changing to the _Preview_ tab triggers a render
* to reproduce:
  1. load docs from repo in dev server
     ```bash
       cd 'docs'
       npm install
       npm run dev
     ```
  2. add a new page with a minimal example of using the `code` extension in `split` mode
     * add file:
       ```text
         src/routes/example/+page.svelte
       ```
     * edit content:
       ```text
         <script lang="ts">
           import { Carta, MarkdownEditor } from 'carta-md'
           import { code } from '@cartamd/plugin-code'

           import 'carta-md/default.css'

           const carta = new Carta({
             extensions: [
               code()
             ]
           })

           export let value = "```js\nconsole.log('Hello, World!');\n```"
         </script>

         <MarkdownEditor mode="split" {value} {carta} />
       ```
  3. open in browser: [example](http://localhost:5173/example)
     * before manually interacting with the textarea
       - input is styled
       - output is not styles
       - js console has log of error:<br>`Uncaught (in promise) ShikiError: Language `js` not found, you may need to load it first`
     * enter any character in the textarea
       - output is re-rendered and is now styled
       - js console does not display any additional errors

**Pull request merged**
